In [2]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt

In [2]:
os.getcwd()

'/Users/lye/Downloads/MDA/Github-MDA2024/2_Notebooks/1_Preprocessing'

In [3]:
itv = pd.read_parquet(
    '/Users/lye/Downloads/MDA/Github-MDA2024/1_Data/CLEANED/interventions_dataset.parquet',
    engine='pyarrow')

itv.head()

,mission_id,service_name,postalcode_permanence,cityname_permanence,streetname_permanence,housenumber_permanence,latitude_permanence,longitude_permanence,permanence_short_name,permanence_long_name,...,t0_Year,t0_DayName,t7_Hour,t7_Day,t7_Month,t7_Year,t7_DayName,province_intervention,intervention_time_(t1confirmed),departure_time_(t1confirmed)
0,20222490011,FB PDS BRUX [PASI CitÈ] SIAMU,1000.0,Brussel (Brussel),Vesaliusstraat,None,50.85097,4.36411,ABBRUX11A,AMB CITE 2,...,2022.0,Tuesday,9.0,6.0,9.0,2022.0,Tuesday,None,NaN,NaN
1,20222490011,FB PDS BRUX [PASI CitÈ] SIAMU,1000.0,Brussel (Brussel),Vesaliusstraat,None,50.85097,4.36411,ABBRUX03A,AMB HELI 3,...,2022.0,Tuesday,10.0,6.0,9.0,2022.0,Tuesday,None,NaN,NaN
2,20222490012,HB UR BRUX CHU St Pierre,1000.0,Brussel (Brussel),Rue Haute,None,50.83433,4.34545,ABBRUX06A,AMB HSP 1,...,2022.0,Tuesday,9.0,6.0,9.0,2022.0,Tuesday,None,NaN,NaN
3,20222490015,FB PDS BRUX [PASI CitÈ] SIAMU,1000.0,Brussel (Brussel),Vesaliusstraat,None,50.85097,4.36411,ABBRUX03A,AMB HELI 3,...,2022.0,Tuesday,11.0,6.0,9.0,2022.0,Tuesday,None,NaN,NaN
4,20222490019,FB PDS WOLL [PASI UCL] SIAMU,1200.0,Woluwe-Saint-Lambert (Woluwe-Saint-Lambert),Avenue Hippocrate - Hippokrateslaan,None,50.85211,4.46040,ABWOLL01A,AMB UCL 1,...,2022.0,Tuesday,11.0,6.0,9.0,2022.0,Tuesday,None,NaN,NaN

In [4]:
itv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1043637 entries, 0 to 1043636
Data columns (total 56 columns):
 #   Column                            Non-Null Count    Dtype
---  ------                            --------------    -----
 0   mission_id                        1043637 non-null  int64
 1   service_name                      948460 non-null   object
 2   postalcode_permanence             714925 non-null   float64
 3   cityname_permanence               749242 non-null   object
 4   streetname_permanence             751636 non-null   object
 5   housenumber_permanence            37640 non-null    object
 6   latitude_permanence               876272 non-null   float64
 7   longitude_permanence              956054 non-null   float64
 8   permanence_short_name             1041012 non-null  object
 9   permanence_long_name              948629 non-null   object
 10  vector_type                       1026228 non-null  object
 11  eventtype_firstcall               717510 non-null   object
 12  eventlevel_firstcall              692288 non-null   object
 13  eventtype_trip                    1042341 non-null  object
 14  eventlevel_trip                   1018682 non-null  object
 15  postalcode_intervention           284 non-null      object
 16  cityname_intervention             1043430 non-null  object
 17  latitude_intervention             952878 non-null   float64
 18  longitude_intervention            1042883 non-null  float64
 19  t0                                1039919 non-null  object
 20  t1                                1025955 non-null  object
 21  t1confirmed                       587886 non-null   object
 22  t2                                858963 non-null   object
 23  t3                                819140 non-null   object
 24  t4                                707672 non-null   object
 25  t5                                642585 non-null   object
 26  t6                                749791 non-null   object
 27  t7                                615385 non-null   object
 28  t9                                8963 non-null     object
 29  intervention_time_(t1reported)    893366 non-null   float64
 30  waiting_time                      629835 non-null   float64
 31  intervention_duration             542655 non-null   float64
 32  departure_time_(t1reported)       935015 non-null   float64
 33  unavailable_time                  10913 non-null    float64
 34  name_destination_hospital         758029 non-null   object
 35  postalcode_destination_hospital   19 non-null       object
 36  cityname_destination_hospital     531658 non-null   object
 37  streetname_destination_hospital   531288 non-null   object
 38  housenumber_destination_hospital  316 non-null      object
 39  calculated_traveltime_destinatio  453973 non-null   float64
 40  calculated_distance_destination   453973 non-null   float64
 41  number_of_transported_persons     458894 non-null   float64
 42  abandon_reason                    109196 non-null   object
 43  t0_Hour                           1039919 non-null  float64
 44  t0_Day                            1039919 non-null  float64
 45  t0_Month                          1039919 non-null  float64
 46  t0_Year                           1039919 non-null  float64
 47  t0_DayName                        1039919 non-null  object
 48  t7_Hour                           615388 non-null   float64
 49  t7_Day                            615388 non-null   float64
 50  t7_Month                          615388 non-null   float64
 51  t7_Year                           615388 non-null   float64
 52  t7_DayName                        615388 non-null   object
 53  province_intervention             891184 non-null   object
 54  intervention_time_(t1confirmed)   637722 non-null   float64
 55  departure_time_(t1confirmed)      661780 non-null   float64
dtypes: float64(23), int64(1), object(32)
memory usage: 445.9+ MB

In [5]:
itv_ca = pd.read_parquet(
    '/Users/lye/Downloads/MDA/Github-MDA2024/1_Data/CLEANED/subset_cardiac.parquet',
    engine='pyarrow')

itv_ca.head()

,mission_id,service_name,postalcode_permanence,cityname_permanence,streetname_permanence,housenumber_permanence,latitude_permanence,longitude_permanence,permanence_short_name,permanence_long_name,...,t0_Year,t0_DayName,t7_Hour,t7_Day,t7_Month,t7_Year,t7_DayName,province_intervention,intervention_time_(t1confirmed),departure_time_(t1confirmed)
205,20222490200,FB PDS ANDE [PASI Anderlecht] SIAMU,1070.0,Anderlecht,Bergense Steenweg,None,50.832540,4.311990,ABANDE03A,AMB AND 3,...,2022.0,Tuesday,18.0,6.0,9.0,2022.0,Tuesday,None,NaN,NaN
206,20222490200,HB UR BRUX CUH Erasme,1070.0,Anderlecht (Anderlecht),joseph wybranlaan,None,50.813960,4.259420,UBANDE01A,SMUR ERASME 1,...,2022.0,Tuesday,19.0,6.0,9.0,2022.0,Tuesday,None,NaN,NaN
207,20222490200,FB PDS ANDE [PASI Anderlecht] SIAMU,1070.0,Anderlecht,Bergense Steenweg,None,50.832540,4.311990,ABANDE02A,AMB AND 2,...,2022.0,Tuesday,NaN,NaN,NaN,NaN,None,None,NaN,NaN
316,20222500029,HB UR BRUX Iris Sud Etterbeek,1050.0,Elsene (Elsene),Rue Jean Paquot,None,50.825831,4.378717,UBIXEL01A,SMUR XL 1,...,2022.0,Wednesday,1.0,7.0,9.0,2022.0,Wednesday,None,NaN,NaN
317,20222500029,FB PDS IXEL [PASI Delta] SIAMU,1050.0,Elsene,Boulevard du Triomphe,None,50.818870,4.403110,ABIXEL02A,AMB DELTA 2,...,2022.0,Wednesday,1.0,7.0,9.0,2022.0,Wednesday,None,NaN,NaN

In [6]:
itv_ca.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13568 entries, 205 to 1043592
Data columns (total 56 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   mission_id                        13568 non-null  int64
 1   service_name                      12435 non-null  object
 2   postalcode_permanence             8543 non-null   float64
 3   cityname_permanence               8692 non-null   object
 4   streetname_permanence             8760 non-null   object
 5   housenumber_permanence            326 non-null    object
 6   latitude_permanence               11746 non-null  float64
 7   longitude_permanence              12908 non-null  float64
 8   permanence_short_name             13564 non-null  object
 9   permanence_long_name              12435 non-null  object
 10  vector_type                       13489 non-null  object
 11  eventtype_firstcall               8612 non-null   object
 12  eventlevel_firstcall              8578 non-null   object
 13  eventtype_trip                    13568 non-null  object
 14  eventlevel_trip                   13567 non-null  object
 15  postalcode_intervention           2 non-null      object
 16  cityname_intervention             13568 non-null  object
 17  latitude_intervention             12337 non-null  float64
 18  longitude_intervention            13562 non-null  float64
 19  t0                                13504 non-null  object
 20  t1                                13489 non-null  object
 21  t1confirmed                       8554 non-null   object
 22  t2                                11087 non-null  object
 23  t3                                10459 non-null  object
 24  t4                                5366 non-null   object
 25  t5                                2481 non-null   object
 26  t6                                10447 non-null  object
 27  t7                                7695 non-null   object
 28  t9                                1 non-null      object
 29  intervention_time_(t1reported)    11571 non-null  float64
 30  waiting_time                      7436 non-null   float64
 31  intervention_duration             7404 non-null   float64
 32  departure_time_(t1reported)       12300 non-null  float64
 33  unavailable_time                  1 non-null      float64
 34  name_destination_hospital         2710 non-null   object
 35  postalcode_destination_hospital   0 non-null      object
 36  cityname_destination_hospital     1473 non-null   object
 37  streetname_destination_hospital   1473 non-null   object
 38  housenumber_destination_hospital  0 non-null      object
 39  calculated_traveltime_destinatio  1285 non-null   float64
 40  calculated_distance_destination   1285 non-null   float64
 41  number_of_transported_persons     1164 non-null   float64
 42  abandon_reason                    3253 non-null   object
 43  t0_Hour                           13504 non-null  float64
 44  t0_Day                            13504 non-null  float64
 45  t0_Month                          13504 non-null  float64
 46  t0_Year                           13504 non-null  float64
 47  t0_DayName                        13504 non-null  object
 48  t7_Hour                           7695 non-null   float64
 49  t7_Day                            7695 non-null   float64
 50  t7_Month                          7695 non-null   float64
 51  t7_Year                           7695 non-null   float64
 52  t7_DayName                        7695 non-null   object
 53  province_intervention             12903 non-null  object
 54  intervention_time_(t1confirmed)   8878 non-null   float64
 55  departure_time_(t1confirmed)      9469 non-null   float64
dtypes: float64(23), int64(1), object(32)
memory usage: 5.9+ MB

In [7]:
itv_ca.rename(columns={
    'latitude_intervention': 'lat_itv',
    'longitude_intervention': 'lon_itv',
    'province_intervention': 'province'
}, inplace=True) ## rename columns

itv_ca = itv_ca.dropna(subset=['lat_itv', 'lon_itv'])  ## drop rows with missing values
itv_ca.reset_index(drop=True, inplace=True)

itv_ca.head()

,mission_id,service_name,postalcode_permanence,cityname_permanence,streetname_permanence,housenumber_permanence,latitude_permanence,longitude_permanence,permanence_short_name,permanence_long_name,...,t0_Year,t0_DayName,t7_Hour,t7_Day,t7_Month,t7_Year,t7_DayName,province,intervention_time_(t1confirmed),departure_time_(t1confirmed)
0,20222490200,FB PDS ANDE [PASI Anderlecht] SIAMU,1070.0,Anderlecht,Bergense Steenweg,None,50.832540,4.311990,ABANDE03A,AMB AND 3,...,2022.0,Tuesday,18.0,6.0,9.0,2022.0,Tuesday,None,NaN,NaN
1,20222490200,HB UR BRUX CUH Erasme,1070.0,Anderlecht (Anderlecht),joseph wybranlaan,None,50.813960,4.259420,UBANDE01A,SMUR ERASME 1,...,2022.0,Tuesday,19.0,6.0,9.0,2022.0,Tuesday,None,NaN,NaN
2,20222490200,FB PDS ANDE [PASI Anderlecht] SIAMU,1070.0,Anderlecht,Bergense Steenweg,None,50.832540,4.311990,ABANDE02A,AMB AND 2,...,2022.0,Tuesday,NaN,NaN,NaN,NaN,None,None,NaN,NaN
3,20222500029,HB UR BRUX Iris Sud Etterbeek,1050.0,Elsene (Elsene),Rue Jean Paquot,None,50.825831,4.378717,UBIXEL01A,SMUR XL 1,...,2022.0,Wednesday,1.0,7.0,9.0,2022.0,Wednesday,None,NaN,NaN
4,20222500029,FB PDS IXEL [PASI Delta] SIAMU,1050.0,Elsene,Boulevard du Triomphe,None,50.818870,4.403110,ABIXEL02A,AMB DELTA 2,...,2022.0,Wednesday,1.0,7.0,9.0,2022.0,Wednesday,None,NaN,NaN

In [8]:
import geopandas as gpd

geo_path = '/Users/lye/Downloads/MDA/Github-MDA2024/1_Data/Belgium.provinces.WGS84.geojson'
geo_be = gpd.read_file(geo_path)

geo_be.head(10)

,RecId,Version,AdPrKey,AdReKey,AdCoKey,NameFRE,NameDUT,NameGER,FiscSitId,UpdDate,Stat_Area,Shape_Leng,Shape_Area,geometry
0,301,1,04000,04000,01000,Région de Bruxelles-Capitale,Brussels Hoofdstedelijk Gewest,Region Brüssel-Hauptstadt,5,2020-03-26 00:00:00+00:00,16242,72162.139042,1.624198e+08,"POLYGON ((4.31176 50.79743, 4.33110 50.77551, ..."
1,302,1,10000,02000,01000,Province d’Anvers,Provincie Antwerpen,Provinz Antwerpen,5,2020-03-26 00:00:00+00:00,287612,409230.640917,2.876120e+09,"MULTIPOLYGON (((5.23796 51.26127, 5.22609 51.2..."
2,303,1,20001,02000,01000,Province du Brabant flamand,Provincie Vlaams-Brabant,Provinz Flämisch-Brabant,5,2020-03-26 00:00:00+00:00,211836,508851.938964,2.118360e+09,"POLYGON ((5.10360 50.70921, 5.10788 50.71839, ..."
3,304,1,20002,03000,01000,Province du Brabant wallon,Provincie Waals-Brabant,Provinz Wallonisch-Brabant,5,2020-03-26 00:00:00+00:00,109718,285898.405104,1.097184e+09,"POLYGON ((5.01955 50.75072, 5.00348 50.76604, ..."
4,305,1,30000,02000,01000,Province de Flandre occidentale,Provincie West-Vlaanderen,Provinz Westflandern,5,2020-03-26 00:00:00+00:00,319658,357083.649169,3.196576e+09,"POLYGON ((3.45892 50.76469, 3.48862 50.78600, ..."
5,306,1,40000,02000,01000,Province de Flandre orientale,Provincie Oost-Vlaanderen,Provinz Ostflandern,5,2020-03-26 00:00:00+00:00,300706,404804.243717,3.007064e+09,"POLYGON ((4.24215 51.35401, 4.16610 51.29283, ..."
6,307,1,50000,03000,01000,Province de Hainaut,Provincie Henegouwen,Provinz Hennegau,5,2020-03-26 00:00:00+00:00,381283,679704.608795,3.812832e+09,"MULTIPOLYGON (((3.17814 50.75616, 3.18736 50.7..."
7,308,1,60000,03000,01000,Province de Liège,Provincie Luik,Provinz Lüttich,5,2020-03-26 00:00:00+00:00,385710,574836.392063,3.857105e+09,"POLYGON ((5.39302 50.37941, 5.39558 50.38374, ..."
8,309,1,70000,02000,01000,Province de Limbourg,Provincie Limburg,Provincie Limburg,5,2020-03-26 00:00:00+00:00,242742,398314.827791,2.427425e+09,"MULTIPOLYGON (((5.68796 50.81200, 5.67841 50.8..."
9,310,1,80000,03000,01000,Province de Luxembourg,Provincie Luxemburg,Provinz Luxembourg,5,2020-03-26 00:00:00+00:00,445926,542458.940272,4.459264e+09,"POLYGON ((4.96864 49.80156, 4.99836 49.79956, ..."

In [9]:
geo_be['NameDUT'].value_counts()

NameDUT
Brussels Hoofdstedelijk Gewest    1
Provincie Antwerpen               1
Provincie Vlaams-Brabant          1
Provincie Waals-Brabant           1
Provincie West-Vlaanderen         1
Provincie Oost-Vlaanderen         1
Provincie Henegouwen              1
Provincie Luik                    1
Provincie Limburg                 1
Provincie Luxemburg               1
Provincie Namen                   1
Name: count, dtype: int64

In [10]:
from shapely import geometry as geo
from shapely.validation import explain_validity
# Assuming Belgian provinces are polygons in the geojson file
# We can check the in which province the intervention is located
point = geo.Point(itv_ca.loc[0, 'lon_itv'], itv_ca.loc[0, 'lat_itv'])
geo_be[geo_be.geometry.contains(point)]['NameDUT'].values[0]

'Brussels Hoofdstedelijk Gewest'

In [14]:
# Check if the geometries are valid

for i in range(len(geo_be)):
    if not geo_be.loc[i, 'geometry'].is_valid:
        print(explain_validity(geo_be.loc[i, 'geometry']))
        geo_be.loc[i, 'geometry'] = geo_be.loc[i, 'geometry'].buffer(0)
        print(geo_be.loc[i, 'geometry'].is_valid)

In [15]:
def get_province(df, geo_df):
    province = []
    missing_province = 0
    for i in range(len(df)):
        point = geo.Point(df.loc[i, 'lon_itv'], df.loc[i, 'lat_itv'])
        contained = geo_df.loc[geo_df['geometry'].contains(point)]['NameDUT'].values
        if contained.size > 0:
            province.append(contained[0])
        else:
            province.append(None)
            missing_province += 1

    df['province'] = province
    print(f'{missing_province} coordinates are not located in any province')

    return df


itv_ca_with_province = get_province(itv_ca, geo_be)
itv_ca_with_province['province'].value_counts()

34 coordinates are not located in any province

province
Provincie Antwerpen               2353
Provincie Oost-Vlaanderen         2184
Provincie Vlaams-Brabant          1516
Provincie Luik                    1386
Provincie Henegouwen              1233
Provincie West-Vlaanderen         1132
Provincie Limburg                  839
Brussels Hoofdstedelijk Gewest     642
Provincie Namen                    435
Provincie Luxemburg                347
Provincie Waals-Brabant            236
Name: count, dtype: int64

In [16]:
itv_ca_with_province.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12337 entries, 0 to 12336
Data columns (total 56 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   mission_id                        12337 non-null  int64
 1   service_name                      11206 non-null  object
 2   postalcode_permanence             7321 non-null   float64
 3   cityname_permanence               7470 non-null   object
 4   streetname_permanence             7531 non-null   object
 5   housenumber_permanence            291 non-null    object
 6   latitude_permanence               11674 non-null  float64
 7   longitude_permanence              11765 non-null  float64
 8   permanence_short_name             12334 non-null  object
 9   permanence_long_name              11207 non-null  object
 10  vector_type                       12258 non-null  object
 11  eventtype_firstcall               7383 non-null   object
 12  eventlevel_firstcall              7359 non-null   object
 13  eventtype_trip                    12337 non-null  object
 14  eventlevel_trip                   12336 non-null  object
 15  postalcode_intervention           0 non-null      object
 16  cityname_intervention             12337 non-null  object
 17  lat_itv                           12337 non-null  float64
 18  lon_itv                           12337 non-null  float64
 19  t0                                12273 non-null  object
 20  t1                                12258 non-null  object
 21  t1confirmed                       8553 non-null   object
 22  t2                                11084 non-null  object
 23  t3                                10456 non-null  object
 24  t4                                5364 non-null   object
 25  t5                                2481 non-null   object
 26  t6                                10444 non-null  object
 27  t7                                7692 non-null   object
 28  t9                                1 non-null      object
 29  intervention_time_(t1reported)    10513 non-null  float64
 30  waiting_time                      6380 non-null   float64
 31  intervention_duration             6337 non-null   float64
 32  departure_time_(t1reported)       11141 non-null  float64
 33  unavailable_time                  1 non-null      float64
 34  name_destination_hospital         2485 non-null   object
 35  postalcode_destination_hospital   0 non-null      object
 36  cityname_destination_hospital     1248 non-null   object
 37  streetname_destination_hospital   1248 non-null   object
 38  housenumber_destination_hospital  0 non-null      object
 39  calculated_traveltime_destinatio  1060 non-null   float64
 40  calculated_distance_destination   1060 non-null   float64
 41  number_of_transported_persons     995 non-null    float64
 42  abandon_reason                    2802 non-null   object
 43  t0_Hour                           12273 non-null  float64
 44  t0_Day                            12273 non-null  float64
 45  t0_Month                          12273 non-null  float64
 46  t0_Year                           12273 non-null  float64
 47  t0_DayName                        12273 non-null  object
 48  t7_Hour                           7692 non-null   float64
 49  t7_Day                            7692 non-null   float64
 50  t7_Month                          7692 non-null   float64
 51  t7_Year                           7692 non-null   float64
 52  t7_DayName                        7692 non-null   object
 53  province                          12303 non-null  object
 54  intervention_time_(t1confirmed)   7847 non-null   float64
 55  departure_time_(t1confirmed)      8339 non-null   float64
dtypes: float64(23), int64(1), object(32)
memory usage: 5.3+ MB

In [17]:
itv_ca_with_province = itv_ca_with_province.dropna(subset=['province'])

itv_ca_with_province.to_csv(
    '/Users/lye/Downloads/MDA/Github-MDA2024/1_Data/CLEANED/subset_ca_with_province.csv',
    index=False)

In [18]:
## Do the same for the full intervention dataset

itv.rename(columns={
    'latitude_intervention': 'lat_itv',
    'longitude_intervention': 'lon_itv',
    'province_intervention': 'province'
}, inplace=True)  ## rename columns

itv = itv.dropna(subset=['lat_itv', 'lon_itv'])  ## drop rows with missing values
itv.reset_index(drop=True, inplace=True)


itv_with_province = get_province(itv, geo_be)
itv_with_province['province'].value_counts()

680 coordinates are not located in any province

province
Brussels Hoofdstedelijk Gewest    144890
Provincie Henegouwen              131127
Provincie Antwerpen               128729
Provincie Oost-Vlaanderen         116792
Provincie Luik                     96970
Provincie West-Vlaanderen          93225
Provincie Vlaams-Brabant           87027
Provincie Limburg                  51315
Provincie Namen                    46914
Provincie Waals-Brabant            31516
Provincie Luxemburg                23319
Name: count, dtype: int64

In [19]:
itv_with_province = itv_with_province.dropna(subset=['province'])
itv_with_province.to_csv(
    '/Users/lye/Downloads/MDA/Github-MDA2024/1_Data/CLEANED/interventions_with_province.csv',
    index=False)

In [5]:
itv_aed_related_with_province = itv_with_province[itv_with_province['eventtype_trip'].isin(['P003 - Cardiac arrest', 'P039 - Cardiac problem (other than thoracic pain)',
                                                            'P019 - Unconscious - syncope'])]
itv_aed_related_with_province.to_csv('/Users/lye/Downloads/MDA/Github-MDA2024/1_Data/CLEANED/interventions_aed_related_with_province.csv', index=False)

In [27]:
aed = pd.read_csv('/Users/lye/Downloads/MDA/Github-MDA2024/1_Data/CLEANED/aed_location_latlon.csv')
aed.head()

,id,type,address,number,postal_code,municipality,province,location,public,available,hours,full_address,lat,lon
0,13.0,NaN,Blvd. fr. roosevelt,24.0,7060,Soignies,Hainaut,NaN,Y,NaN,NaN,"Blvd. fr. roosevelt, 7060 Soignies, Hainaut",50.576042,4.065740
1,70.0,NaN,Ch. de wégimont,76.0,4630,Ayeneux,Liège,NaN,NaN,NaN,NaN,"Ch. de wégimont, 4630 Ayeneux, Liège",50.607680,5.730187
2,71.0,NaN,Place saint-lambert,NaN,4020,Liège,Liège,NaN,NaN,NaN,NaN,"Place saint-lambert, 4020 Liège, Liège",50.645622,5.573620
3,72.0,NaN,Rue du doyard,NaN,4990,Lierneux,Liège,NaN,NaN,NaN,NaN,"Rue du doyard, 4990 Lierneux, Liège",50.287416,5.786325
4,73.0,NaN,Fond saint servais,NaN,4000,Liège,Liège,NaN,NaN,NaN,NaN,"Fond saint servais, 4000 Liège, Liège",50.646806,5.571031

In [28]:
aed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15775 entries, 0 to 15774
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            15775 non-null  float64
 1   type          5661 non-null   object
 2   address       15775 non-null  object
 3   number        13577 non-null  float64
 4   postal_code   15775 non-null  int64
 5   municipality  15775 non-null  object
 6   province      15775 non-null  object
 7   location      8962 non-null   object
 8   public        8656 non-null   object
 9   available     4739 non-null   object
 10  hours         1148 non-null   object
 11  full_address  15775 non-null  object
 12  lat           15775 non-null  float64
 13  lon           15775 non-null  float64
dtypes: float64(4), int64(1), object(9)
memory usage: 1.7+ MB

In [29]:
aed['province'].value_counts()

province
Antwerpen            2355
Bruxelles-brussel    2117
Hainaut              1950
Liège                1771
Oost-vlaanderen      1664
West-vlaanderen      1374
Vlaams-brabant       1282
Limburg               998
Namur                 900
Luxembourg            683
Brabant wallon        681
Name: count, dtype: int64

In [23]:
def get_medical_province(df, geo_df):
    province = []
    missing_province = 0
    for i in range(len(df)):
        point = geo.Point(df.loc[i, 'lon'], df.loc[i, 'lat'])
        contained = geo_df.loc[geo_df['geometry'].contains(
            point)]['NameDUT'].values
        if contained.size > 0:
            province.append(contained[0])
        else:
            province.append(None)
            missing_province += 1

    df['province'] = province
    print(f'{missing_province} coordinates are not located in any province')

    return df


aed_with_province = get_medical_province(aed, geo_be)
aed_with_province['province'].value_counts()

29 coordinates are not located in any province

province
Provincie Antwerpen               2356
Brussels Hoofdstedelijk Gewest    2106
Provincie Henegouwen              1947
Provincie Luik                    1770
Provincie Oost-Vlaanderen         1677
Provincie West-Vlaanderen         1382
Provincie Vlaams-Brabant          1274
Provincie Limburg                  992
Provincie Namen                    900
Provincie Waals-Brabant            676
Provincie Luxemburg                666
Name: count, dtype: int64

In [25]:
aed_with_province.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15775 entries, 0 to 15774
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            15775 non-null  float64
 1   type          5661 non-null   object
 2   address       15775 non-null  object
 3   number        13577 non-null  float64
 4   postal_code   15775 non-null  int64
 5   municipality  15775 non-null  object
 6   province      15746 non-null  object
 7   location      8962 non-null   object
 8   public        8656 non-null   object
 9   available     4739 non-null   object
 10  hours         1148 non-null   object
 11  full_address  15775 non-null  object
 12  lat           15775 non-null  float64
 13  lon           15775 non-null  float64
dtypes: float64(4), int64(1), object(9)
memory usage: 1.7+ MB

In [30]:
mug = pd.read_csv('/Users/lye/Downloads/MDA/Github-MDA2024/1_Data/CLEANED/mug_location_latlon.csv')
mug.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 94 entries, 0 to 93
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   hospital_id     94 non-null     int64
 1   mug_id          94 non-null     int64
 2   campus_id       94 non-null     int64
 3   name_hospital   94 non-null     object
 4   name_campus     59 non-null     object
 5   address_campus  94 non-null     object
 6   postal_code     94 non-null     int64
 7   municipality    94 non-null     object
 8   region          94 non-null     object
 9   province        94 non-null     object
 10  full_address    94 non-null     object
 11  id              94 non-null     int64
 12  lat             94 non-null     float64
 13  lon             94 non-null     float64
dtypes: float64(2), int64(5), object(7)
memory usage: 10.4+ KB

In [31]:
mug['province'].value_counts()

province
Henegouwen                        16
Antwerpen                         15
Oost-vlaanderen                   12
West-vlaanderen                   10
Brussels hoofdstedelijk gewest     9
Limburg                            7
Luik                               7
Vlaams-brabant                     5
Namen                              4
Luxemburg                          4
Waals-brabant                      3
Lüttich                            2
Name: count, dtype: int64

In [32]:
pit = pd.read_csv('/Users/lye/Downloads/MDA/Github-MDA2024/1_Data/CLEANED/pit_location_latlon.csv')
pit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   unit           24 non-null     object
 1   campus         24 non-null     object
 2   province       21 non-null     object
 3   region         24 non-null     object
 4   unit_id        24 non-null     object
 5   ambucode       24 non-null     int64
 6   ambusitecode   24 non-null     int64
 7   link           2 non-null      object
 8   hospital_name  24 non-null     object
 9   campus_name    24 non-null     object
 10  lat            23 non-null     float64
 11  lon            23 non-null     float64
dtypes: float64(2), int64(2), object(8)
memory usage: 2.4+ KB

In [36]:
pit.rename(columns={'hospital_name': 'name_hospital'}, inplace=True)
hospital_1 = pit[['name_hospital', 'province', 'lat', 'lon']]
hospital_2 = mug[['name_hospital', 'province', 'lat', 'lon']]
hospital = pd.concat([hospital_1, hospital_2], axis=0)
hospital.drop_duplicates(subset=['lat', 'lon'], keep='first', inplace=True)
hospital.reset_index(drop=True, inplace=True)
hospital.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117 entries, 0 to 116
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name_hospital  117 non-null    object
 1   province       114 non-null    object
 2   lat            116 non-null    float64
 3   lon            116 non-null    float64
dtypes: float64(2), object(2)
memory usage: 3.8+ KB

In [37]:
hospital.to_csv('/Users/lye/Downloads/MDA/Github-MDA2024/1_Data/CLEANED/hospital.csv', index=False)